name: health_care
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.1.2
  google_fonts: 6.1.0
  validadores: ^1.0.8
  brasil_fields: ^1.14.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  http: 1.2.0
  path_provider: ^2.1.2
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.7
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  babstrap_settings_screen: ^0.1.6
  firebase_storage: ^11.6.9
  open_app_file: ^4.0.2
  file_picker: ^8.0.0+1
  pdf: ^3.10.8
  printing: ^5.12.0
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  url_launcher: ^6.2.6
  open_file: ^3.3.2
  flutter_media_downloader: ^1.0.4
  flutter_downloader: ^1.11.7
  flutter_file_downloader: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  percent_indicator: ^4.2.3
  firebase_messaging: ^14.7.19
  firebase_app_check: ^0.2.1+17


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
